# NUMPY PRACTICE ASSIGNMENT

**Topics:** Arrays, vectorization, broadcasting, statistics, and linear algebra  
**Language:** Python  
**Main library:** NumPy

## Learning Objectives

After completing this notebook, learners will be able to:

- Create and inspect one-dimensional, two-dimensional, and multidimensional NumPy arrays.
- Apply indexing, slicing, Boolean filtering, and reshaping.
- Stack, split, and transform arrays.
- Use vectorized operations, broadcasting, and axis-based aggregation.
- Apply universal functions, descriptive statistics, and `NaN` handling.
- Perform basic linear-algebra operations.
- Generate reproducible random data.
- Compare Python-loop performance with NumPy vectorization.
- Apply NumPy to image data and portfolio calculations.

## Submission Rules

For each exercise, present your work in this order:

1. **Code**
2. **Output**
3. **A brief explanation of 1-3 sentences**

Additional rules:

- Do not use `for` loops unless an exercise explicitly allows them.
- Always print `shape` when working with two-dimensional arrays or broadcasting.
- Do not modify the provided input data directly unless the exercise asks you to.
- Run the **Automatic Check** cells after completing the relevant exercises.


## Part 0 - Environment Setup

In [2]:
import time
import numpy as np

# function to format the output of a numpy array
np.set_printoptions(
    precision=4,
    suppress=True
)

print("NumPy version:", np.__version__)

NumPy version: 2.4.6


---

# PART 1 - INTRODUCTION TO NUMPY ARRAYS

## Exercise 1. Scalars and a One-Dimensional Vector

Given:

```python
a = 10
b = 3.14
v = np.array([1, 2, 3])
```

### Tasks

1. Print the types of `a` and `b`.
2. Print `v`.
3. Print `v.shape`, `v.ndim`, `v.size`, and `v.dtype`.
4. Explain:
   - What is a scalar in mathematics or data analysis?
   - What do `shape`, `ndim`, and `size` represent?


In [3]:
# Write your solution here

a = 10
b = 3.14
v = np.array([1, 2, 3])

# TODO
print(type(a))
print(type(b))
print(type(v))

print(isinstance(a, int))
print(isinstance(b, float))
print(isinstance(v, np.ndarray))

print(v.dtype, v.shape, v.ndim, v.size  )

<class 'int'>
<class 'float'>
<class 'numpy.ndarray'>
True
True
True
int64 (3,) 1 3


**Student explanation:**

- 

In [ ]:
# Automatic check - run after completing the exercise
try:
    assert isinstance(v, np.ndarray)
    assert v.shape == (3,)
    assert v.ndim == 1
    assert v.size == 3
    print("Basic requirements satisfied.")
except Exception as e:
    print("Not yet satisfied:", e)

## Exercise 2. Fast Array Creation

Create and print the following arrays:

1. `z`: an array of zeros with shape `(2, 3)`.
2. `o`: an array of ones with shape `(3, 3)`.
3. `f`: an array with shape `(2, 4)` in which every value is `7`.
4. `r`: the even integers from `0` to less than `10`.
5. `l`: five evenly spaced values from `0` to `1`, including both endpoints.
6. `I`: a fourth-order identity matrix.

Print the `shape` of every array.


In [ ]:
# Write your solution here

z = np.zeros((2, 3))
print(z)

o = np.ones((3,3))
print(o)

f = np.full((2, 4), 7)
print(f)

r = np.arange(0, 10, 2)
print(r)

l = np.linspace(0, 1, 5)
print(l)

I = np.eye(4)
print(I)    

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7 7]
 [7 7 7 7]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**Student explanation:**

- Compare `np.arange()` and `np.linspace()`.
- 

In [12]:
# Automatic check
try:
    assert z.shape == (2, 3)
    assert o.shape == (3, 3)
    assert f.shape == (2, 4)
    assert np.array_equal(r, np.array([0, 2, 4, 6, 8]))
    assert l.shape == (5,)
    assert I.shape == (4, 4)
    # assert np.allclose(I, np.eye(4))
    print("Requirements satisfied.")
except Exception as e:
    print("Not yet satisfied:", e)

Requirements satisfied.


## Exercise 3. Data Types and Memory

Given:

```python
x = np.array([1, 2, 3, 4], dtype=np.int64)
```

### Tasks

1. Print `x.dtype`, `x.itemsize`, and `x.nbytes`.
2. Convert `x` to `int16` and store the result in `x16`.
3. Print `x16.dtype`, `x16.itemsize`, and `x16.nbytes`.
4. Create `y = np.array([1.2, 2.8, 3.5])` and convert it to `int32`.
5. Explain what happens to the fractional parts.


In [20]:
# Write your solution here

x = np.array([1, 2, 3, 4], dtype=np.int64)

print(x)

print(x.dtype, x.itemsize, x.nbytes)

x16 = x.astype(np.int16)

print(x16.dtype, x16.itemsize, x16.nbytes)

y = np.array([1.2, 2.8, 3.5],np.float32)
print(y)
print(y.dtype, y.itemsize, y.nbytes)

y32 = y.astype(dtype = np.int32)

print(y32)
print(y32.dtype, y32.itemsize, y32.nbytes)  

# TODO

[1 2 3 4]
int64 8 32
int16 2 8
[1.2 2.8 3.5]
float32 4 12
[1 2 3]
int32 4 12


**Student explanation:**

- 

---

# PART 2 - INDEXING, SLICING, AND RESHAPING

## Exercise 4. One-Dimensional Indexing and Slicing

Given:

```python
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

### Tasks

1. Print `a[1]`.
2. Print `a[1:4]`.
3. Print `a[::2]`.
4. Create `b = a.copy()` and then assign `b[3:7] = -1`.
5. Print both `a` and `b`.
6. Explain:
   - Before which index does `a[1:4]` stop?
   - What does `a[::2]` mean?


In [22]:
# Write your solution here

a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# TODO

print(a[1])
print(a[1:4])
print(a[::2])    

b = a.copy()
b[3:7] = -1

print(a, b)

1
[1 2 3]
[0 2 4 6 8]
[0 1 2 3 4 5 6 7 8 9] [ 0  1  2 -1 -1 -1 -1  7  8  9]


**Student explanation:**

- 

## Exercise 5. Two-Dimensional Indexing and Boolean Filtering

Given:

```python
M = np.array([
    [10, 11, 12],
    [20, 21, 22],
    [30, 31, 32]
])
```

### Tasks

1. Print `M` and `M.shape`.
2. Extract the element at row index 1 and column index 0.
3. Extract the entire second column.
4. Extract the entire last row.
5. Extract the `2 x 2` block in the upper-left corner.
6. Filter all values greater than or equal to `22`.
7. Print the shape of each result.
8. Explain why Boolean filtering often returns a one-dimensional array.


In [30]:
# Write your solution here

M = np.array([
    [10, 11, 12],
    [20, 21, 22],
    [30, 31, 32]
])

# TODO

print(M)
print(M.shape)
print(M[1,0])
print(M[:,1])
print(M[-1,:])
print(M[0:2,0:2])
print(M > 22)


[[10 11 12]
 [20 21 22]
 [30 31 32]]
(3, 3)
20
[11 21 31]
[30 31 32]
[[10 11]
 [20 21]]
[[False False False]
 [False False False]
 [ True  True  True]]


**Student explanation:**

- 

## Exercise 6. Views and Copies

Given:

```python
a = np.array([10, 20, 30, 40, 50])
```

### Tasks

1. Create `view = a[1:4]`.
2. Create `copy = a[1:4].copy()`.
3. Change the first element of `view` to `999`.
4. Change the first element of `copy` to `-999`.
5. Print `a`, `view`, and `copy`.
6. Explain the difference between a view and a copy.


In [31]:
# Write your solution here

a = np.array([10, 20, 30, 40, 50])

# TODO

view = a[1:4]
view[0] = 999

copy = a[1:4].copy()
copy[0] = -999

print(view)
print(copy)

[999  30  40]
[-999   30   40]


**Student explanation:**

- 

## Exercise 7. Reshape, Flatten, and Ravel

Given:

```python
a = np.arange(1, 13)
```

### Tasks

1. Reshape `a` into matrix `A` with shape `(3, 4)`.
2. Reshape `a` into matrix `B` with two rows and let NumPy infer the number of columns.
3. Flatten `A` with `flatten()` and store it in `flat_copy`.
4. Flatten `A` with `ravel()` and store it in `flat_view`.
5. Print every shape.
6. Change the first element of `flat_view` and observe `A`.
7. Restore the data if needed before continuing.


In [38]:
# Write your solution here

a = np.arange(1, 13)

# TODO

A = a.reshape((3, 4))

print(A)

B = a.reshape((2,-1))

print(B)

flat_copy = a.flatten()

print(flat_copy)

ravel_copy = a.ravel()

print(ravel_copy)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


**Student explanation:**

- 

## Exercise 8. Stacking and Splitting Arrays

Given:

```python
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
```

### Tasks

1. Stack vertically into `vertical`.
2. Stack horizontally into `horizontal`.
3. Use `np.stack(..., axis=1)` to create `columns`.
4. Create `x = np.arange(12).reshape(3, 4)`.
5. Split `x` into two equal parts by columns.
6. Print every result and shape.


In [ ]:
# Write your solution here

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# TODO

print(np.vstack((a,b)))
print(np.hstack((a,b)))



[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


**Student explanation:**

- Compare `vstack`, `hstack`, and `stack`.
- 

---

# PART 3 - OPERATIONS, BROADCASTING, AND AGGREGATION

## Exercise 9. Vector Operations and Dot Product

Given:

```python
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
```

### Tasks

1. Compute `x + y`.
2. Compute `x * y`.
3. Compute the dot product with `np.dot(x, y)`.
4. Compute the Euclidean norm of `x` with `np.linalg.norm(x)`.
5. Round the norm to three decimal places.
6. Explain the difference between `x * y` and `np.dot(x, y)`.


In [6]:
# Write your solution here

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

# TODO

import math 

print(x + y)
print(x * y)
print(np.dot(x, y))
print(np.round(np.linalg.norm(x),3))
print(np.round(np.linalg.norm(y),3))

[5 7 9]
[ 4 10 18]
32
3.742
8.775


**Student explanation:**

- 

## Exercise 10. Broadcasting Between a Two-Dimensional and a One-Dimensional Array

Given:

```python
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([1, 0, 1])
```

### Tasks

1. Compute `C = A + B`.
2. Print `A`, `B`, and `C`.
3. Print `A.shape`, `B.shape`, and `C.shape`.
4. Explain:
   - Which broadcasting rule allows `(2, 3)` to work with `(3,)`?
   - Along which dimension is `B` extended?


In [48]:
# Write your solution here

A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([1, 0, 1])

C = A + B
print(C )

print(A.shape, B.shape, C.shape)

# TODO

[[2 2 4]
 [5 5 7]]
(2, 3) (3,) (2, 3)


**Student explanation:**

- 

In [ ]:
# Automatic check
try:
    expected = np.array([
        [2, 2, 4],
        [5, 5, 7]
    ])
    assert np.array_equal(C, expected)
    assert C.shape == (2, 3)
    print("Requirements satisfied.")
except Exception as e:
    print("Not yet satisfied:", e)

## Exercise 11. Column-Wise Broadcasting

Given:

```python
A = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

column = np.array([1, 2, 3]).reshape(-1, 1)
```

### Tasks

1. Compute `B = A + column`.
2. Print `A.shape`, `column.shape`, and `B.shape`.
3. Explain why `reshape(-1, 1)` is required.
4. Try adding `A` to `np.array([1, 2, 3])` and compare the broadcasting direction.


In [10]:
# Write your solution here

A = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

column = np.array([1, 2, 3]).reshape(-1, 1)

print(A)
print(column)

B = A + column
print(B)

C = A + column.T
print(C)
# TODO

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[1]
 [2]
 [3]]
[[11 21 31]
 [42 52 62]
 [73 83 93]]
[[11 22 33]
 [41 52 63]
 [71 82 93]]


**Student explanation:**

- 

## Exercise 12. Aggregation Along Axes

Given:

```python
A = np.array([
    [2, 4, 6],
    [1, 3, 5],
    [7, 8, 9]
])
```

### Tasks

1. Compute the sum of the entire array.
2. Compute the column-wise sums.
3. Compute the row-wise sums.
4. Compute the column-wise means.
5. Compute the row-wise maximum values.
6. Print the shape of every result.
7. Explain the meanings of `axis=0` and `axis=1`.


In [ ]:
# Write your solution here

A = np.array([
    [2, 4, 6],
    [1, 3, 5],
    [7, 8, 9]
])

# TODO
sum_all = np.sum(A)
sum_rows = np.sum(A, axis = 1) # row có index là 1
sum_cols = np.sum(A, axis = 0) # column có index là 0

print("Sum of all elements:", sum_all)
print("Sum of each row:", sum_rows)
print("Sum of each column:", sum_cols)

mean_cols = np.mean(A, axis = 0 )
print("Mean of each column:", mean_cols)
max_rows =np.max(A,axis = 1)
print("Max of each row:", max_rows)

 

Sum of all elements: 45
Sum of each row: [12  9 24]
Sum of each column: [10 15 20]
Mean of each column: [3.3333 5.     6.6667]
Max of each row: [6 5 9]


**Student explanation:**

- 

## Exercise 13. Universal Functions and Vectorized Conditions

Given:

```python
x = np.array([-4.0, -1.0, 0.0, 1.0, 4.0])
```

### Tasks

1. Compute the absolute values.
2. Compute the square roots of the absolute values.
3. Compute the exponential values.
4. Use `np.where()` to assign:
   - `"negative"` when the value is below 0;
   - `"zero"` when the value equals 0;
   - `"positive"` when the value is above 0.
5. Do not use a loop.


In [17]:
# Write your solution here

x = np.array([-4.0, -1.0, 0.0, 1.0, 4.0])

# TODO

abs_x =np.abs(x)
print("Absolute values:", abs_x)

sqrt_abs_x = np.sqrt(abs_x)
print("Square roots of absolute values:", sqrt_abs_x)
assign =np.where(x<0,'Negative','non-negative')

print("Assignment based on condition:", assign)

Absolute values: [4. 1. 0. 1. 4.]
Square roots of absolute values: [2. 1. 0. 1. 2.]
Assignment based on condition: ['Negative' 'Negative' 'non-negative' 'non-negative' 'non-negative']


**Student explanation:**

- 

## Exercise 14. Column-Wise Z-Score Standardization

Given:

```python
scores = np.array([
    [50, 60, 70],
    [80, 90, 75],
    [60, 65, 85]
], dtype=float)
```

### Tasks

1. Compute the mean of each column as `mu`.
2. Compute the standard deviation of each column as `sigma`.
3. Compute `Z = (scores - mu) / sigma`.
4. Print `mu`, `sigma`, and `Z`.
5. Print the shape of every variable.
6. Verify that each column mean of `Z` is approximately 0.
7. Verify that each column standard deviation of `Z` is approximately 1.


In [ ]:
# Write your solution here

scores = np.array([
    [50, 60, 70],
    [80, 90, 75],
    [60, 65, 85]
], dtype=float)

# TODO

mu = np.mean(scores, axis = 0 )
sigma = np.std(scores, axis = 0)
z = (scores - mu) / sigma

print(mu, sigma, z)

print(mu.shape, sigma.shape, z.shape)


[63.3333 71.6667 76.6667] [12.4722 13.1233  6.2361] [[-1.069  -0.889  -1.069 ]
 [ 1.3363  1.397  -0.2673]
 [-0.2673 -0.508   1.3363]]
(3,) (3,) (3, 3)


**Student explanation:**

- What does `axis=0` mean?
- Why does `scores - mu` work?
- 

In [23]:
# Automatic check
try:
    assert mu.shape == (3,)
    assert sigma.shape == (3,)
    assert z.shape == scores.shape
    assert np.allclose(z.mean(axis=0), 0)
    assert np.allclose(z.std(axis=0), 1)
    print("Requirements satisfied.")
except Exception as e:
    print("Not yet satisfied:", e)

Requirements satisfied.


---

# PART 4 - RANDOM NUMBERS, STATISTICS, AND MISSING DATA

## Exercise 15. Reproducible Random-Number Generation

### Tasks

1. Create `rng = np.random.default_rng(42)`.
2. Generate:
   - 10 integers from 1 to 99;
   - 1,000 values from a standard normal distribution;
   - 1,000 values from a uniform distribution on `[0, 1)`;
   - 1,000 values from a Poisson distribution with `lam=3`.
3. Print the first 10 values of each large array.
4. Compute the mean and standard deviation of the standard-normal sample.
5. Recreate the generator with the same seed and verify whether the two integer sequences are identical.


In [ ]:
# Write your solution here

# TODO

**Student explanation:**

- What is the role of the seed?
- 

## Exercise 16. Descriptive Statistics and `ddof`

Given:

```python
data = np.array([12, 15, 18, 20, 25, 30, 18, 22], dtype=float)
```

### Tasks

Compute and print:

1. Mean.
2. Median.
3. Population variance.
4. Sample variance.
5. Population standard deviation.
6. Sample standard deviation.
7. The 25th, 50th, and 75th percentiles.
8. Range.
9. Explain the difference between `ddof=0` and `ddof=1`.


In [ ]:
# Write your solution here

data = np.array([12, 15, 18, 20, 25, 30, 18, 22], dtype=float)

# TODO

**Student explanation:**

- 

## Exercise 17. Handling `NaN`

Given:

```python
data = np.array([
    10.0,
    np.nan,
    20.0,
    30.0,
    np.nan,
    40.0
])
```

### Tasks

1. Print the Boolean mask identifying `NaN` positions.
2. Count the missing values.
3. Compute the ordinary mean and observe the result.
4. Compute the mean, median, and standard deviation while ignoring `NaN`.
5. Create `clean_data` containing only valid values.
6. Create `filled_data` in which every `NaN` is replaced by the median.
7. Do not use a loop.


In [ ]:
# Write your solution here

data = np.array([
    10.0,
    np.nan,
    20.0,
    30.0,
    np.nan,
    40.0
])

# TODO

**Student explanation:**

- 

---

# PART 5 - LINEAR ALGEBRA

## Exercise 18. Basic Matrix Operations

Given:

```python
A = np.array([
    [1, 2],
    [3, 4]
], dtype=float)

B = np.array([
    [2, 0],
    [1, 2]
], dtype=float)
```

### Tasks

1. Compute `A * B`.
2. Compute `A @ B`.
3. Compute the transpose of `A`.
4. Compute the determinant of `A`.
5. Compute the inverse of `A`.
6. Verify whether `A @ inv_A` is approximately the identity matrix.
7. Explain the difference between `*` and `@`.


In [ ]:
# Write your solution here

A = np.array([
    [1, 2],
    [3, 4]
], dtype=float)

B = np.array([
    [2, 0],
    [1, 2]
], dtype=float)

# TODO

**Student explanation:**

- 

## Exercise 19. Solving a Linear System

Given the system \(Ax=b\):

```python
A = np.array([
    [2, 1],
    [1, 3]
], dtype=float)

b = np.array([8, 13], dtype=float)
```

### Tasks

1. Solve for `x` with `np.linalg.solve()`.
2. Print `x`.
3. Verify the solution with `A @ x`.
4. Compute the residual `A @ x - b`.
5. Compute the norm of the residual vector.


In [ ]:
# Write your solution here

A = np.array([
    [2, 1],
    [1, 3]
], dtype=float)

b = np.array([8, 13], dtype=float)

# TODO

**Student explanation:**

- 

## Exercise 20. Eigenvalues and Eigenvectors

Given:

```python
A = np.array([
    [4, 2],
    [1, 3]
], dtype=float)
```

### Tasks

1. Compute the eigenvalues and eigenvectors.
2. Print the results and their shapes.
3. Select the first eigenvalue as `lambda_1` and the corresponding eigenvector as `v_1`.
4. Verify the relationship `A @ v_1 ≈ lambda_1 * v_1`.


In [ ]:
# Write your solution here

A = np.array([
    [4, 2],
    [1, 3]
], dtype=float)

# TODO

**Student explanation:**

- 

---

# PART 6 - PERFORMANCE AND APPLICATIONS

## Exercise 21. Vectorization Versus a Python Loop

> This is the only exercise in the notebook in which a `for` loop is allowed.

Given:

```python
n = 2_000_000
x = np.arange(n)
y = np.arange(n)
```

### Tasks

1. Add the two arrays with a Python loop and measure the time.
2. Add them with `x + y` and measure the time.
3. Print both execution times.
4. Verify the results with `np.array_equal()`.
5. Compute the ratio `t_loop / t_vec`.
6. Explain why vectorization is usually faster.


In [ ]:
# Write your solution here

n = 2_000_000
x = np.arange(n)
y = np.arange(n)

# Hint:
# start = time.perf_counter()
# res_loop = np.empty(n, dtype=np.int64)
# for i in range(n):
#     res_loop[i] = x[i] + y[i]
# t_loop = time.perf_counter() - start

# TODO

**Student explanation:**

- 

## Exercise 22. Image Processing with NumPy Arrays

Given the grayscale-image matrix:

```python
image = np.array([
    [0, 40, 80, 120],
    [160, 200, 240, 255],
    [30, 60, 90, 120],
    [150, 180, 210, 240]
], dtype=np.uint8)
```

### Tasks

1. Print `image.shape` and `image.dtype`.
2. Create an image that is 30 units brighter while keeping all values in `[0, 255]`.
3. Create an inverted image with `255 - image`.
4. Create a binary image:
   - 255 for values greater than or equal to 128;
   - 0 for values below 128.
5. Do not use a loop.
6. Avoid integer overflow when increasing brightness.


In [ ]:
# Write your solution here

image = np.array([
    [0, 40, 80, 120],
    [160, 200, 240, 255],
    [30, 60, 90, 120],
    [150, 180, 210, 240]
], dtype=np.uint8)

# TODO

**Student explanation:**

- Why should the data be converted to a larger numeric type before addition?
- 

## Exercise 23. Finance Application - Gold Portfolio Value

Given:

```python
prices = np.array(
    [1900, 1910, 1905, 1920, 1930],
    dtype=float
)

lot_size = 100
lots = 5
```

### Tasks

1. Compute the daily portfolio values:
   `values = prices * lot_size * lots`.
2. Compute daily returns:
   `returns = (prices[1:] - prices[:-1]) / prices[:-1]`.
3. Compute cumulative growth:
   `growth = np.cumprod(1 + returns)`.
4. Compute the running peak of `values`.
5. Compute the drawdown for each day.
6. Compute the maximum drawdown.
7. Print every result and shape.


In [ ]:
# Write your solution here

prices = np.array(
    [1900, 1910, 1905, 1920, 1930],
    dtype=float
)

lot_size = 100
lots = 5

# TODO

**Student explanation:**

- Why is `returns` one element shorter than `prices`?
- What is the financial meaning of `np.cumprod()`?
- What does drawdown measure?
- 

## Exercise 24. Multi-Asset Portfolio and Weights

Given:

```python
P = np.array([
    [1900, 25.0, 70],
    [1910, 26.0, 68],
    [1905, 25.5, 71],
    [1920, 27.0, 69],
    [1930, 28.0, 72]
], dtype=float)

lots = np.array([5, 200, 10])
lot_size = np.array([100, 1, 10])
```

Each row represents one day, and each column represents one asset.

### Tasks

1. Compute the daily value of each asset:
   `V = P * lots * lot_size`.
2. Compute the total portfolio value for each day.
3. Compute the asset weights:
   `weights = V / total.reshape(-1, 1)`.
4. Print `P.shape`, `V.shape`, `total.shape`, and `weights.shape`.
5. Verify that the daily weights sum to approximately 1.
6. Use `np.argmax()` to identify the asset with the largest weight each day.


In [ ]:
# Write your solution here

P = np.array([
    [1900, 25.0, 70],
    [1910, 26.0, 68],
    [1905, 25.5, 71],
    [1920, 27.0, 69],
    [1930, 28.0, 72]
], dtype=float)

lots = np.array([5, 200, 10])
lot_size = np.array([100, 1, 10])

# TODO

**Student explanation:**

- Why is `reshape(-1, 1)` needed when calculating the weights?
- 

In [ ]:
# Automatic check
try:
    assert V.shape == P.shape
    assert total.shape == (P.shape[0],)
    assert weights.shape == P.shape
    assert np.allclose(weights.sum(axis=1), 1)
    print("Requirements satisfied.")
except Exception as e:
    print("Not yet satisfied:", e)

---

# PART 7 - INTEGRATED EXERCISE

## Exercise 25. Analyze a Data Matrix with NumPy

Given eight observations and four variables:

```python
X = np.array([
    [12,  5, 100, 1],
    [15,  7, 120, 0],
    [11,  6,  95, 1],
    [20, 10, 160, 0],
    [18,  9, 150, 1],
    [14,  8, 110, 0],
    [17,  7, 140, 1],
    [16,  6, 130, 0]
], dtype=float)
```

### Tasks

Do not use a loop:

1. Print the shape, number of dimensions, and data type.
2. Compute the mean, median, and standard deviation of each column.
3. Standardize the first three columns with Z-scores while keeping the last column unchanged.
4. Filter rows whose first-column value is greater than that column's mean.
5. Compute the correlation matrix of the first three columns with `np.corrcoef(..., rowvar=False)`.
6. Find the row index containing the largest value in the third column.
7. Sort the data in ascending order by the third column using `np.argsort()`.
8. Write a brief interpretation of the results.


In [ ]:
# Write your solution here

X = np.array([
    [12,  5, 100, 1],
    [15,  7, 120, 0],
    [11,  6,  95, 1],
    [20, 10, 160, 0],
    [18,  9, 150, 1],
    [14,  8, 110, 0],
    [17,  7, 140, 1],
    [16,  6, 130, 0]
], dtype=float)

# TODO

**Student interpretation:**

- 

---

# Self-Assessment

Mark the topics you can now complete:

- [ ] Create arrays with `array`, `zeros`, `ones`, `full`, `arange`, and `linspace`.
- [ ] Read `shape`, `ndim`, `size`, and `dtype`.
- [ ] Use indexing, slicing, and Boolean filtering.
- [ ] Distinguish between views and copies.
- [ ] Use `reshape`, `flatten`, `ravel`, `stack`, and `split`.
- [ ] Apply vectorized operations.
- [ ] Understand broadcasting and axis-based aggregation.
- [ ] Use statistical functions and handle `NaN`.
- [ ] Perform linear-algebra operations.
- [ ] Generate random values with a seed.
- [ ] Compare Python-loop and vectorized performance.
- [ ] Apply NumPy to image and financial data.
